First implementation of the authentication chain with LDAP
sitmun/sitmun-backend-core pull request #153
Opened 2023-04-25 08:19 UTC by albertobucesGdtl

The authentication chain configuration is found in WebSecurityController. Ldap requires a password encoder in its configuration, it has been set to sha256 (which is marked as deprecated because of its poor security), in case the ldap server used has a different encryption, the encoder would have to be changed.

Includes class LdapUserAuthoritiesPopulator to check the user name in database and get its authorizations when LDAP authentication is active.

The properties for configuring authentication with ldap are in app/src/main/resources/config/application-dev.yml and app/src/main/resources/config/application-prod.yml.

2023-04-26 10:02 UTC, fjlopez requested changes
Please review the comments. Make sure that the tests in `common` and `deploy/heroku-dev-full` pass in local. 

Use an approach similar to https://spring.io/guides/gs/authenticating-ldap/ to validate the behavior of the LDAP support without depending on a Guadaltel LDAP server.

2023-05-04 17:26 UTC, fjlopez commented on common/build.gradle
> +  implementation 'com.unboundid:unboundid-ldapsdk'
unboundid-ldapsdk must be only available in tests

2023-05-04 17:27 UTC, fjlopez commented on common/src/main/java/org/sitmun/authentication/controller/AuthenticationController.java
> +}
Add a blank line at the end to be identical

2023-05-04 17:30 UTC, fjlopez commented on common/src/main/java/org/sitmun/infrastructure/security/storage/UserDetailsPasswordStorage.java
> +@Order(2)
Remove (2). Then the default value applies: Ordered.LOWEST_PRECEDENCE. This component must be always the last.

2023-05-04 17:33 UTC, fjlopez commented on deploy/heroku-dev-full/src/test/java/org/sitmun/authentication/controller/AuthenticationControllerTest.java
>  }
An additional cases must be tested: if the user exists in LDAP but not in the SITMUN database, the login must fail.

2023-05-04 17:37 UTC, fjlopez requested changes
Change requests focus on the need of an additional test and  the documentation of the two tests

2023-05-05 08:26 UTC, albertobucesGdtl commented
The requested changes have been made.

2023-05-15 22:41 UTC, fjlopez commented
The code seems ok but we are waiting some technical specs from Diputaciò Lleida which are required for a final confirmation.

2023-07-13 10:45 UTC, albertobucesGdtl commented
Updated LDAP tests

2023-07-17 15:34 UTC, merged

2023-07-17 15:43 UTC, fjlopez commented
Some tests were internally broken due to bad configuration options. Redundant files have been removed. 

**Required**

- Tests must be updated to support the LDIF configuration of Diputació de Lleida https://github.com/albertobucesGdtl/sitmun-backend-core/pull/1 


**Actions expected**

- @albertobucesGdtl, do an additional PR with the LDAP tests based on the LDIF configuration of **Diputació de Lleida** rather than on the Spring Framework example.