First implementation of the api of configuration and authorization
sitmun/sitmun-backend-core pull request #155
Opened 2023-05-12 09:50 UTC by albertobucesGdtl

Implementation of the proxy configuration and authorization service.
Including classes for the different responses returned by the service and a configuration property indicating the validity time of the returned configuration.
Tests have also been implemented to test the functionality.

2023-05-15 22:32 UTC, fjlopez requested changes
Please check the comments in this review.

2023-05-15 22:32 UTC, fjlopez commented on common/src/main/java/org/sitmun/authorization/service/ProxyConfigurationService.java
> +	@Value("${sitmun.proxy.config-response-validity-in-seconds}")
Response validity time must be extracted from the token of authenticated users. 
The value of this field should be used only for public users.

2023-05-15 22:32 UTC, fjlopez commented on common/src/main/java/org/sitmun/authorization/service/ProxyConfigurationService.java
> +@org.springframework.stereotype.Service
Import Service

2023-05-15 22:32 UTC, fjlopez commented on common/src/main/java/org/sitmun/authorization/dto/HttpSecurityDto.java
> +@Builder
Remove `serialVersionUID` and `Serializable`

2023-05-15 22:32 UTC, fjlopez commented on common/src/main/java/org/sitmun/authorization/dto/OgcWmsPayloadDto.java
> +@JsonTypeName("OgcWmsPayload")
Remove `serialVersionUID` and `Serializable`

2023-05-15 22:32 UTC, fjlopez commented on common/src/main/java/org/sitmun/authorization/service/ProxyConfigurationService.java
> +		if(CONNECTION_TYPE_KEY.equalsIgnoreCase(configProxyRequest.getType())) {
Compute first the `PayloadDto`, and then build the `ConfigProxyDto`. Do not replicate `ConfigProxyDto` builder several times. Note that this simplifies the code as the logic for the exp will be in the same place. If f`vary` field is more logical to be part of `PayloadDto`, we will update the API spec accordingly

2023-05-15 22:32 UTC, fjlopez commented on common/src/main/java/org/sitmun/authorization/service/ProxyConfigurationService.java
> +		return result;
What happens when `result` is `null`? The request is probably wrong. Fail fast, throw an exception that returns a 401.

2023-05-15 22:32 UTC, fjlopez commented on deploy/heroku-dev-lite/src/test/java/org/sitmun/authorization/controller/ProxyConfigurationControllerTest.java
Can you confirm that this test in heroku-dev-lite passes in your machine?

2023-05-15 22:32 UTC, fjlopez commented on deploy/heroku-dev-full/src/test/java/org/sitmun/authorization/controller/ProxyConfigurationControllerTest.java
> +  @Value("${security.authentication.jwt.secret}")
This is not the secret that the proxy is using. It is `security.authentication.middleware.secret`.

2023-05-15 22:32 UTC, fjlopez commented on common/src/main/java/org/sitmun/authorization/service/ProxyConfigurationService.java
> +		return sql;
What happens when the SQL is an empty string? The request is probably wrong. Fail fast, throw an exception that returns a 401.

2023-05-16 13:47 UTC, albertobucesGdtl commented on common/src/main/java/org/sitmun/authorization/service/ProxyConfigurationService.java
> +@org.springframework.stereotype.Service
The Service tag cannot be imported because there is already an import from org.sitmun.domain.service.Service.

2023-05-16 13:52 UTC, albertobucesGdtl commented on deploy/heroku-dev-lite/src/test/java/org/sitmun/authorization/controller/ProxyConfigurationControllerTest.java
The test service identifiers have been modified to match existing ones in the heroku-dev-lite database and are now working.
The task identifiers for jdbc connections have also been modified but there are no tasks with related connections and these tests do not work.

2023-05-16 13:54 UTC, albertobucesGdtl commented
The requested changes have been made.
Please check the comments on some of the requested changes in the review.

2023-05-17 15:00 UTC, merged